# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    authentication_admin_handler:
        class: BackendBundle\Handler\AuthenticationHandler
        public: false
        arguments:  ['@router', '@service_container']
    
    logout_admin_handler:
        class: BackendBundle\Handler\LogoutHandler
        arguments:  ['@router'] 
        
    fos_user.resetting.form.type:
        class: FrontendBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: fos_user_resetting }
