<?php

namespace ModelBundle\Entity;

/**
 * AlertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertaRepository extends \Doctrine\ORM\EntityRepository
{
}
