<?php

namespace ModelBundle\Entity;

/**
 * CapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
