<?php

namespace ModelBundle\Entity;

/**
 * CentroRecoleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroRecoleccionRepository extends \Doctrine\ORM\EntityRepository
{
}
