<?php

namespace ModelBundle\Entity;

/**
 * ComponentePMIRSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentePMIRSRepository extends \Doctrine\ORM\EntityRepository
{
}
