<?php

namespace ModelBundle\Entity;

/**
 * DisposicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisposicionRepository extends \Doctrine\ORM\EntityRepository
{
}
