<?php

namespace ModelBundle\Entity;

/**
 * EmpresaRecolectoraResiduosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRecolectoraResiduosRepository extends \Doctrine\ORM\EntityRepository
{
}
