<?php

namespace ModelBundle\Entity;

/**
 * PreguntaPMIRSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaPMIRSRepository extends \Doctrine\ORM\EntityRepository
{
}
