<?php

namespace ModelBundle\Entity;

/**
 * PreguntaSeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaSeguimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
