<?php

namespace ModelBundle\Entity;

/**
 * ProgramacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramacionRepository extends \Doctrine\ORM\EntityRepository
{
}
