<?php

namespace ModelBundle\Entity;

/**
 * RecoleccionVolquetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecoleccionVolquetaRepository extends \Doctrine\ORM\EntityRepository
{
}
