<?php

namespace ModelBundle\Entity;

/**
 * RecoleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecoleccionRepository extends \Doctrine\ORM\EntityRepository
{
}
