<?php

namespace ModelBundle\Entity;

/**
 * RecoleccionContenedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecoleccionContenedorRepository extends \Doctrine\ORM\EntityRepository
{
}
