<?php

namespace ModelBundle\Entity;

/**
 * ResiduoRecoleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResiduoRecoleccionRepository extends \Doctrine\ORM\EntityRepository
{
}
