<?php

namespace ModelBundle\Entity;

/**
 * ResiduoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResiduoRepository extends \Doctrine\ORM\EntityRepository
{
}
