<?php

namespace ModelBundle\Entity;

/**
 * SeguimientoPMIRSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoPMIRSRepository extends \Doctrine\ORM\EntityRepository
{
}
