<?php

namespace ModelBundle\Entity;

/**
 * SoporteModificadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoporteModificadoRepository extends \Doctrine\ORM\EntityRepository
{
}
