<?php

namespace ModelBundle\Entity;

/**
 * SoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
