<?php

namespace ModelBundle\Entity;

/**
 * TipoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
