<?php

namespace ModelBundle\Entity;

/**
 * TipoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
