<?php

namespace ModelBundle\Entity;

/**
 * TipoResiduoTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoResiduoTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
