<?php

namespace ModelBundle\Entity;

/**
 * TipoCapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCapacitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
