<?php

namespace ModelBundle\Entity;

/**
 * ContenedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolquetaRepository extends \Doctrine\ORM\EntityRepository
{
}
